QT.lzma.VERSION = 0.9.9
QT.lzma.name = QtLzma
QT.lzma.module = Qt5Lzma
QT.lzma.libs = $$QT_MODULE_LIB_BASE
QT.lzma.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtLzma
QT.lzma.frameworks =
QT.lzma.bins = $$QT_MODULE_BIN_BASE
QT.lzma.plugin_types =
QT.lzma.depends = core
QT.lzma.run_depends = core
QT.lzma.uses =
QT.lzma.module_config = v2
QT.lzma.CONFIG =
QT.lzma.DEFINES = QT_LZMA_LIB
QT.lzma.enabled_features =
QT.lzma.disabled_features =
QT_CONFIG +=
QT_MODULES += lzma
